//
// Created by Marc on 19/03/2026.
//


#define USERS_FILE "/20users.csv"
#define DOMAINS_FILE "/domains.txt"
#define CONDITION_TERMS_FILE "/Social_Network_Terms.txt"
#define FILES_DIR "/data"
#define CURRENT_DIR "."
#define PARENT_DIR ".."

#ifdef PROJECT_ROOT_DIR
#define USERS_PATH PROJECT_ROOT_DIR FILES_DIR USERS_FILE
#define DOMAINS_PATH PROJECT_ROOT_DIR FILES_DIR DOMAINS_FILE
#define CONDITION_TERMS_PATH PROJECT_ROOT_DIR FILES_DIR CONDITION_TERMS_FILE
#else
#define USERS_PATH PARENT_DIR FILES_DIR USERS_FILE
#define DOMAINS_PATH PARENT_DIR FILES_DIR DOMAINS_FILE
#define CONDITION_TERMS_PATH PARENT_DIR FILES_DIR CONDITION_TERMS_FILE
#endif
